[![pyntcloud logo](../data/pyntcloud.png)](../Index.ipynb)

In [1]:
from pyntcloud import PyntCloud

# PyntCloud.from_file

The simplest way to read point cloud data is using the PyntCloud's methot `from_file`.

In [2]:
ply_cloud = PyntCloud.from_file("../data/python_bin.ply")
ply_cloud

PyntCloud
=========

38028 points with 6 scalar fields
50704 faces in mesh
0 kdtrees
0 neighbourhoods
0 octrees
0 voxelgrids

Centroid: 6.136162757873535, -6.503418445587158, 1.0

Other attributes:
	 comments: <class 'str'>
	 obj_info: <class 'str'>

In [3]:
ply_cloud.points

          x     y    z  red  green  blue
0      -6.5  -6.5  0.5    0    170   255
1      -6.5  -5.5  0.5    0    170   255
2      -5.5  -5.5  0.5    0    170   255
3      -5.5  -6.5  0.5    0    170   255
4      -5.5  -6.5  1.5    0    170   255
5      -5.5  -5.5  1.5    0    170   255
6      -6.5  -5.5  1.5    0    170   255
7      -6.5  -6.5  1.5    0    170   255
8      -4.5  -5.5  0.5    0    170   255
9      -4.5  -6.5  0.5    0    170   255
10     -4.5  -6.5  1.5    0    170   255
11     -4.5  -5.5  1.5    0    170   255
12     -3.5  -5.5  0.5    0    170   255
13     -3.5  -6.5  0.5    0    170   255
14     -3.5  -6.5  1.5    0    170   255
15     -3.5  -5.5  1.5    0    170   255
16     -2.5  -5.5  0.5    0    170   255
17     -2.5  -6.5  0.5    0    170   255
18     -2.5  -6.5  1.5    0    170   255
19     -2.5  -5.5  1.5    0    170   255
20     -1.5  -5.5  0.5    0    170   255
21     -1.5  -6.5  0.5    0    170   255
22     -1.5  -6.5  1.5    0    170   255
23     -1.5  -5.5  1.5    0    170   255
24     -0.5  -5.5  0.5    0    170   255
25     -0.5  -6.5  0.5    0    170   255
26     -0.5  -6.5  1.5    0    170   255
27     -0.5  -5.5  1.5    0    170   255
28      0.5  -5.5  0.5    0    170   255
29      0.5  -6.5  0.5    0    170   255
...     ...   ...  ...  ...    ...   ...
37998  52.5  33.5  0.5  255    255     0
37999  52.5  33.5  1.5  255    255     0
38000  53.5  33.5  0.5  255    255     0
38001  53.5  33.5  1.5  255    255     0
38002  54.5  33.5  0.5  255    255     0
38003  54.5  33.5  1.5  255    255     0
38004  55.5  33.5  0.5  255    255     0
38005  55.5  33.5  1.5  255    255     0
38006  56.5  33.5  0.5  255    255     0
38007  56.5  33.5  1.5  255    255     0
38008  50.5  34.5  0.5  255    255     0
38009  50.5  34.5  1.5  255    255     0
38010  51.5  34.5  0.5  255    255     0
38011  51.5  34.5  1.5  255    255     0
38012  52.5  34.5  0.5  255    255     0
38013  52.5  34.5  1.5  255    255     0
38014  53.5  34.5  0.5  255    255     0
38015  53.5  34.5  1.5  255    255     0
38016  64.5  22.5  0.5  255    255     0
38017  64.5  22.5  1.5  255    255     0
38018  65.5  22.5  0.5  255    255     0
38019  65.5  22.5  1.5  255    255     0
38020  64.5  23.5  0.5  255    255     0
38021  64.5  23.5  1.5  255    255     0
38022  65.5  23.5  0.5  255    255     0
38023  65.5  23.5  1.5  255    255     0
38024  64.5  24.5  0.5  255    255     0
38025  64.5  24.5  1.5  255    255     0
38026  64.5  25.5  0.5  255    255     0
38027  64.5  25.5  1.5  255    255     0

[38028 rows x 6 columns]

In [4]:
ply_cloud.mesh

       n_points     v1     v2     v3
0             3    210    211    212
1             3    210    212    213
2             3    210    214    215
3             3    210    215    211
4             3    212    216    217
5             3    212    217    213
6             3    211    218    219
7             3    211    219    212
8             3    211    215    220
9             3    211    220    218
10            3    219    221    216
11            3    219    216    212
12            3    218    222    223
13            3    218    223    219
14            3    218    220    224
15            3    218    224    222
16            3    223    225    221
17            3    223    221    219
18            3    222    226    227
19            3    222    227    223
20            3    222    224    228
21            3    222    228    226
22            3    227    229    225
23            3    227    225    223
24            3    226    230    231
25            3    226    231    227
26            3    226    228    232
27            3    226    232    230
28            3    231    233    229
29            3    231    229    227
...         ...    ...    ...    ...
50674         3  37375  38019  38017
50675         3  37375  38017  37373
50676         3  37374  38018  38019
50677         3  37374  38019  37375
50678         3  37742  37770  38020
50679         3  37742  38020  38016
50680         3  38017  38021  37771
50681         3  38017  37771  37743
50682         3  38022  38020  38021
50683         3  38022  38021  38023
50684         3  38016  38020  38022
50685         3  38016  38022  38018
50686         3  38019  38023  38021
50687         3  38019  38021  38017
50688         3  38018  38022  38023
50689         3  38018  38023  38019
50690         3  37770  37798  38024
50691         3  37770  38024  38020
50692         3  38021  38025  37799
50693         3  38021  37799  37771
50694         3  38020  38024  38025
50695         3  38020  38025  38021
50696         3  38026  37826  37827
50697         3  38026  37827  38027
50698         3  37798  37826  38026
50699         3  37798  38026  38024
50700         3  38025  38027  37827
50701         3  38025  37827  37799
50702         3  38024  38026  38027
50703         3  38024  38027  38025

[50704 rows x 4 columns]

In [5]:
ply_cloud.comments

['comment Author: David de la Iglesia Castro\r\n']

PyntCloud.from_file supports many different point cloud formats and you can find a list along with their principal charateristics in the [** SUPPORTED FILE FORMATS** notebook](supported file formats.ipynb).

In the docs/data folder there are samples of the same point cloud stored in different formats.

In [19]:
pcd_cloud = PyntCloud.from_file("../data/python.pcd")
mat_cloud = PyntCloud.from_file("../data/python.mat")

print(all(pcd_cloud.points == mat_cloud.points))

print(all(ply_cloud.points == mat_cloud.points))

True
True

# PyntCloud.to_file

The simplest way to write point cloud data is using the PyntCloud's methot `to_file`.

In [20]:
PyntCloud.to_file("out_cloud.npz", points=pcd_cloud.points, important_thing={"Carl": "black", "Lenny": "white"} )

True

In [21]:
writed_cloud = PyntCloud.from_file("out_cloud.npz")

In [22]:
print(all(pcd_cloud.points == writed_cloud.points))

True

In [26]:
writed_cloud.important_thing

TypeError: iteration over a 0-d array